# Generated by Django 3.0.5 on 2021-01-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gugai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('location', models.TextField(max_length=100)),
                ('phonenumber', models.IntegerField()),
                ('cases', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Gugai',
            },
        ),
    ]
