# Generated by Django 3.0.5 on 2021-01-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gugai',
        ),
    ]
