# Generated by Django 3.0.5 on 2021-01-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210104_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=30)),
                ('companyname', models.CharField(max_length=20)),
                ('bottles', models.IntegerField()),
                ('original_amount', models.FloatField()),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
