# Generated by Django 3.0.5 on 2021-01-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Sales'},
        ),
    ]
