# Generated by Django 3.0.5 on 2021-01-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210108_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daily_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
