# Generated by Django 3.0.5 on 2021-01-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home'},
        ),
    ]
