# Generated by Django 3.0.5 on 2021-01-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210109_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='location',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
