# Generated by Django 3.0.5 on 2021-01-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20210105_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thenapattai',
            new_name='Thinnapatti',
        ),
        migrations.AlterModelOptions(
            name='karuppur',
            options={'verbose_name_plural': 'Karuppur'},
        ),
        migrations.AlterModelOptions(
            name='thinnapatti',
            options={'verbose_name_plural': 'Thinnapatti'},
        ),
        migrations.AlterModelOptions(
            name='thirupathi',
            options={'verbose_name_plural': 'C.Thirupathi'},
        ),
    ]
