# Generated by Django 3.0.5 on 2021-01-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20210105_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thirupathi',
            options={'verbose_name_plural': 'Thirupathi'},
        ),
    ]
