# Generated by Django 3.0.5 on 2021-01-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20210105_1233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thirupathi',
        ),
    ]
