# Generated by Django 3.0.5 on 2021-01-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_hogenakkal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edappadi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('address', models.TextField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Edappadi',
            },
        ),
        migrations.CreateModel(
            name='Jalagai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('address', models.TextField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jalagai',
            },
        ),
        migrations.CreateModel(
            name='Mattur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('address', models.TextField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Mattur',
            },
        ),
        migrations.CreateModel(
            name='Mecheri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('address', models.TextField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Mecheri',
            },
        ),
        migrations.CreateModel(
            name='Sankari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('address', models.TextField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sankari',
            },
        ),
        migrations.CreateModel(
            name='Vanavasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('address', models.TextField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vanavasi',
            },
        ),
    ]
